# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Misskey settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - misskey_uid
    - misskey_gid
    - misskey_hostname
    - misskey_path_prefix
    - misskey_container_network
    - misskey_database_hostname
    - misskey_database_password
    - misskey_redis_hostname

- name: Fail if Misskey fulltextSearch provider option is invalid
  ansible.builtin.fail:
    msg: >-
      misskey_config_fulltext_search_provider must be 'meilisearch', 'sqlLike', or 'sqlPgroonga'
  when: "misskey_config_fulltext_search_provider not in ['meilisearch', 'sqlLike', 'sqlPgroonga']"

- name: Fail if Meilisearch settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) when `misskey_config_fulltext_search_provider` is `meilisearch`
  when: "misskey_config_fulltext_search_provider == 'meilisearch' and lookup('vars', item, default='') | string | length == 0"
  with_items:
    - misskey_config_meilisearch_host
    - misskey_config_meilisearch_apikey

- name: Run if Traefik is enabled
  when: misskey_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Misskey are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - misskey_container_labels_traefik_hostname
        - misskey_container_labels_traefik_path_prefix

    - name: Fail if misskey_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          misskey_container_labels_traefik_path_prefix (`{{ misskey_container_labels_traefik_path_prefix }}`) must be `/`.
          Misskey does not support hosting under a subpath yet.
      when: "misskey_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `misskey_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if misskey_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          misskey_container_labels_traefik_path_prefix (`{{ misskey_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/misskey`).
      when: "misskey_container_labels_traefik_path_prefix != '/' and misskey_container_labels_traefik_path_prefix[-1] == '/'"
